WebApplicationCore1/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

[Route("Albums")]
public class AlbumController : Controller
{
    private IAlbumRepository _albumRepo;

    public AlbumController(IAlbumRepository albumRepo)
    {
        _albumRepo = albumRepo;
    }

    [HttpGet("")]
    public async Task<IActionResult> Index()
    {
        var albums = await _albumRepo.GetAll();

        return View(albums);
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetByID(int id)
    {
        var album = await _albumRepo.GetByID(id);
        
        return View(album);
    }
}

WebApplicationCore1/Controllers/PhotoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

[Route("Photos")]
public class PhotoController : Controller
{
    private IPhotoRepository _photoRepo;

    public PhotoController(IPhotoRepository photoRepo)
    {
        _photoRepo = photoRepo;
    }

    [HttpGet("")]
    public async Task<IActionResult> IndexAsync()
    {
        var allPhotos = await _photoRepo.GetAll();

        return View(allPhotos);
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetByIDAsync(int id)
    {
        var photo = await _photoRepo.GetByID(id);

        return View(photo);
    }
}

WebApplicationCore1/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

[Route("Posts")]
public class PostController : Controller
{
    private  IPostRepository _postRepo;

    public PostController(IPostRepository postRepo)
    {
        _postRepo = postRepo;
    }

    [HttpGet("")]
    public async Task<IActionResult> Index()
    {
        return View(await _postRepo.GetAll());
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetByID(int id)
    {
        return View(await _postRepo.GetByID(id));
    }
}

WebApplicationCore1/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

[Route("Users")]
public class UserController : Controller
{
    private IUserRepository _userRepo;
    private IAlbumRepository _albumRepo;
    private IPostRepository _postRepo;

    public UserController(IUserRepository userRepo, IAlbumRepository albumRepo, IPostRepository postRepo)
    {
        _userRepo = userRepo;
        _albumRepo = albumRepo;
        _postRepo = postRepo;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var users = await _userRepo.GetAll();
        return View(users);
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetByID(int id)
    {
        var user = await _userRepo.GetByID(id);
        user.Albums = await _albumRepo.GetForUser(user.ID);
        user.Posts = await _postRepo.GetForUser(user.ID);

        return View(user);
    }
}

WebApplicationCore1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationCore1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Index">Web App Core 1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Post" asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Album" asp-action="Index">Albums</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Photo" asp-action="Index">Photos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Comment" asp-action="Index">Comments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplicationCore1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>